### PR TITLE
Added GenerateClients options for separate generation

### PR DESCRIPTION
**Pull request by berkslv**
I added generateClients options to generate seperate client and contracts. Also add 1 test for this feature

### CODE REVIEW

**Review by christianhelle — CHANGES_REQUESTED** [review]
Great stuff @berkslv 

Thanks for being thorough by updating the docs and tests

I pulled your branch and tried it out locally to review. There is, unfortunately, one thing you missed, and as it is right now, the generated code will not build because the `System.Text.Json.Serialization` has not been imported

To fix this, you need to update `RefitGenerator` and replace lines 128-132

``` csharp
var contracts = RefitInterfaceImports
    .GetImportedNamespaces(settings)
    .Aggregate(
        generator.GenerateFile(),
        (current, import) => current.Replace($"{import}.", string.Empty));
```

with 

```csharp
var contracts = generator.GenerateFile();
if (settings.GenerateClients)
{
    contracts = RefitInterfaceImports
        .GetImportedNamespaces(settings)
        .Aggregate(
            contracts,
            (current, import) => current.Replace($"{import}.", string.Empty));
}
```

**Comment by christianhelle** [comment]
@all-contributors please add @berkslv for ideas and code

**Comment by berkslv** [comment]
I have completed the changes you requested @christianhelle

Thank you for adding me as a contributor, I follow this repo closely in the future and try to add value to it.

**Review by christianhelle — APPROVED** [review]
Works fine and looks good

**Comment by christianhelle** [comment]
Thank you for your contribution @berkslv

**Pull request merged**
