### PR TITLE
Additional Namespaces for generated Types

### PR DESCRIPTION
**Pull request by angelofb**
refitter ./openapi.json --additional-namespace "Your.Additional.Namespace" --additional-namespace "Your.Other.Additional.Namespace" 

generates

```

using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

using Your.Additional.Namespace;
using Your.Other.Additional.Namespace;

namespace GeneratedCode
{
//...
}
```

### CODE REVIEW

**Review by christianhelle — APPROVED** [review]

**Comment by angelofb** [comment]
if i don't generate the models with the option "--interface-only" then I need to specify where the models are defined
        
`
--interface-only                               Don't generate contract types
`

**Comment by christianhelle** [comment]
> if i don't generate the models with the option "--interface-only" then I need to specify where the models are defined
> 
> `--interface-only Don't generate contract types`

Ok. That makes sense.

Thanks again!

**Comment by angelofb** [comment]
Thank you!

**Comment by christianhelle** [comment]
The changes here are now published to nuget.org and released as [v0.6.2](https://github.com/christianhelle/refitter/releases/tag/0.6.2)

**Comment by angelofb** [comment]
nice!

**Pull request merged**
