### PR TITLE
Introduce `--operation-name-template` command line argument

### PR DESCRIPTION
**Pull request by angelofb**
--operation-name-template 

Generate operation names using pattern like '{operationName}Async' 

very simple pattern substitution.
I want to replace nswag with refitter in my codebase and I have so(ooo) many operations already generated with "Async" appended at the end (NSwag generator do this by default, to change the behaviour the template must be edited)

### CODE REVIEW

**Review by christianhelle — CHANGES_REQUESTED** [review]
@angelofb thank you once again for your awesome contributions! This looks good!

If its not too much, may I ask you to apply the same changes to the `GetOperatorName()` method in `RefitMultipleInterfaceByTagGenerator` so that the behavior is consistent?

Maybe we should introduce some validation to ensure that if `--operation-name-template` is provided then it should at least contain the string `{operationName}`, otherwise show a user friendly error message. Command line argument validation is done from `src/Refitter/GenerateCommand.cs` in the `Validate()` method (line 18)

**Comment by christianhelle** [comment]
@angelofb `RefitMultipleInterfaceGenerator` is used for `--multiple-interfaces ByEndpoint`

It generates a separate interface containing a single method called `Execute()` for every operation 

Something like this:

```csharp
public partial interface IUpdatePetEndpoint
{
    /// <summary>
    /// Update an existing pet by Id
    /// </summary>
    [Put("/pet")]
    Task<Pet> Execute([Body] Pet body);
}
```

I don't think applying the `-operation-name-template` makes sense with `-multiple-interfaces ByEndpoint`. Can you revert the changes in `RefitMultipleInterfaceGenerator` ?

The changes in `RefitMultipleInterfaceByTagGenerator` look fine ✅

**Comment by christianhelle** [comment]
> done, out of curiosity what is the use case for RefitMultipleInterfaceGenerator generation? when is better or necessary to use this strategy?

I joined a team 2 years ago that has adopted this standard for REST API clients and it grew on me. So its actually purely for my (and my teams) personal taste

**Review by christianhelle — APPROVED** [review]

**Comment by angelofb** [comment]
🥳

**Pull request merged**
