### PR TITLE
Add support for customizable type and contract generator settings

### PR DESCRIPTION
**Pull request by christianhelle**
The changes here allow customization of the NSwag type and contracts generator through the `.refitter` settings file. This is done by specifying the `codeGeneratorSettings` property, which is documented in the README files and will be included documentation site (https://refitter.github.io) after this is merged

The following OpenAPI spec:

```json
{
  "swagger": "2.0",
  "info": {
    "title": "Dummy API",
    "version": "0.0.0"
  },
  "host": "x.io",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/dummy/{id}": {
      "get": {
        "operationId": "Get Dummy",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "the specific dummy",
            "required": true,
            "format": "int64",
            "type": "integer"
          },
          {
            "name": "valid_from",
            "in": "query",
            "description": "the start of the period",
            "required": true,
            "format": "date",
            "type": "string"
          },
          {
            "name": "valid_to",
            "in": "query",
            "description": "the end of the period",
            "required": true,
            "format": "date",
            "type": "string"
          },
          {
            "name": "test_time",
            "in": "query",
            "description": "test parameter",
            "required": true,
            "format": "time",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "No response was specified"
          }
        }
      }
    }
  }
}
```

used with the following .refitter settings file

```json
{
  "contractsGeneratorSettings": {
    "dateType": "System.DateTime",
    "dateTimeType": "System.DateTime"
  }
}
```

will generated an interface like this:

```csharp
[System.CodeDom.Compiler.GeneratedCode("Refitter", "1.0.0.0")]
public partial interface IDummyAPI
{
    [Get("/t/dummy/{employee_id}")]
    Task GetDummy(
        long employee_id, 
        [Query] System.DateTime valid_from, 
        [Query] System.DateTime valid_to, 
        [Query] System.TimeSpan test_time);
}
```

This implements #186 suggested by @bielik01

`codeGeneratorSettings` exposes the following properties with the following default values:

```json
"codeGeneratorSettings": {
    "namespace": "GeneratedCode",
    "requiredPropertiesMustBeDefined": true,
    "generateDataAnnotations": true,
    "anyType": "object",
    "dateType": "System.DateTimeOffset",
    "dateTimeType": "System.DateTimeOffset",
    "timeType": "System.TimeSpan",
    "timeSpanType": "System.TimeSpan",
    "arrayType": "System.Collections.Generic.ICollection",
    "dictionaryType": "System.Collections.Generic.IDictionary",
    "arrayInstanceType": "System.Collections.ObjectModel.Collection",
    "dictionaryInstanceType": "System.Collections.Generic.Dictionary",
    "arrayBaseType": "System.Collections.ObjectModel.Collection",
    "dictionaryBaseType": "System.Collections.Generic.Dictionary",
    "propertySetterAccessModifier": "",
    "generateImmutableArrayProperties": false,
    "generateImmutableDictionaryProperties": false,
    "handleReferences": false,
    "jsonSerializerSettingsTransformationMethod": null,
    "generateJsonMethods": false,
    "enforceFlagEnums": false,
    "inlineNamedDictionaries": false,
    "inlineNamedTuples": true,
    "inlineNamedArrays": false,
    "generateOptionalPropertiesAsNullable": false,
    "generateNullableReferenceTypes": false,
    "generateNativeRecords": false,
    "generateDefaultValues": true,
    "inlineNamedAny": false,
    "excludedTypeNames": [ ]
  }
```

### CODE REVIEW

**Comment by christianhelle** [comment]
Does this work for you @bielik01 ?

**Comment by bielik01** [comment]
that's more like it, thanks!

**Comment by bielik01** [comment]
although you could also add CodeGeneratorSettingsBase properties, because I'll need ExcludedTypeNames as well

**Comment by christianhelle** [comment]
> although you could also add CodeGeneratorSettingsBase properties, because I'll need ExcludedTypeNames as well

Sure

**Comment by bielik01** [comment]
perfect ❤

**Pull request merged**
