### PR TITLE
Add support for customizing Contracts namespace and output path

### PR DESCRIPTION
**Pull request by christianhelle**
The changes here introduce the `--contracts-output` and `--contracts-namespace` CLI tool argument for customizing the output path for the Contracts file, and also the namespace

This pull request updates the `RefitGeneratorSettings` class to include new properties related to contracts. Specifically, it adds the `ContractsNamespace` property to specify the namespace for the generated contracts, and the `ContractsOutputFolder` property to specify the relative path to the folder where the generated contracts should be stored. These additions provide more flexibility and customization options when generating code with Refit.

Note: The other commits in this pull request are related to file naming constants, updating the `CSharpClientGeneratorFactory` to use the contracts namespace if available, writing the contracts file to the specified output folder, and updating the `Directory.Build.props` file to include all .cs files in the GeneratedCode folder and its subfolders. These changes support the main update to the `RefitGeneratorSettings` class.

With these changes, the following example .refitter file:

```json
{
  "openApiPath": "../OpenAPI/v3.0/petstore.json",
  "namespace": "Petstore",
  "contractsNamespace": "Petstore.Contracts",
  "outputFolder": "Client",
  "contractsOutputFolder": "Contracts",
  "generateMultipleFiles": true,
  "naming": {
    "useOpenApiTitle": false,
    "interfaceName": "SwaggerPetstore"
  },
  "dependencyInjectionSettings": {
    "baseUrl": "https://petstore3.swagger.io/api/v3",
    "transientErrorHandler": "HttpResilience",
    "maxRetryCount": 3,
    "firstBackoffRetryInSeconds": 0.5
  }
}
```

outputs the following structure:

image

### CODE REVIEW

**Comment by christianhelle** [comment]
Will this work for you @berkslv ?

**Comment by smietanka** [comment]
@christianhelle  Hey, are these changes will be soon in next release? I see 1.2.0 version of refitter is from 2 weeks ago, but I cannot see newer version. I would really like to use these features like multiple files or change namespace for contracts and output for contracts :)

**Comment by christianhelle** [comment]
> @christianhelle Hey, are these changes will be soon in next release? I see 1.2.0 version of refitter is from 2 weeks ago, but I cannot see newer version. I would really like to use these features like multiple files or change namespace for contracts and output for contracts :)

@smietanka Thanks for your interest. This feature will be released in v1.2.1. I published a release preview that includes this feature that you can try out in th meantime

```
dotnet tool install --global Refitter --version 1.2.1-preview.54
```

**Comment by berkslv** [comment]
> Will this work for you @berkslv ?

This is really great work, thank you for your efforts on this topic. We will definitely use this feature in our projects. Thank you.

**Pull request merged**
